name: scribe
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.1.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^9.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  flutter_screenutil: ^5.8.4
  routemaster: ^1.0.1
  google_sign_in: ^6.1.4
  google_fonts: ^5.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  flutter_quill: ^7.2.10
  uuid: ^3.0.7
  flutter_native_splash: ^2.3.1
  icons_launcher: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  logger: ^1.4.0

flutter_native_splash:
  color: "#F8EDEB"
  image: "assets/icon/scribe.png"
  android_12:
    image: "assets/icon/scribe.png"

icons_launcher:
  image_path: "assets/icon/scribe.png"
  platforms:
    android:
      enable: true
      adaptive_background_image: "assets/icon/scribe_logo_bg.png"
      adaptive_foreground_image: "assets/icon/scribe_logo_fg.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

